### ISSUE TITLE
500 error when loading /Users sometime after release 0.8.2

### ISSUE THREAD

**Issue by pablodiazgutierrez** [15five/django-scim2#20]
I just updated from 0.5.* to the latest 0.10.6 and noticed I consistently get a 500 error () when loading /Users and /Groups:

> unbound method get_user_model() must be called with UsersView instance as first argument (got nothing instead)

We use Python 2.7 and Django 1.11, and at no point the stack trace shows our internal code:

ERROR 2019-04-14 13:26:16,237 views 31136 139791130908416 Unable to complete SCIM call.
Traceback (most recent call last):
  File "[...]/site-packages/django_scim/views.py", line 90, in dispatch
    return super(SCIMView, self).dispatch(request, *args, **kwargs)
  File "[...]/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "[...]/site-packages/django_scim/views.py", line 246, in get
    return self.get_many(request)
  File "[...]/site-packages/django_scim/views.py", line 262, in get_many
    extra_filter_kwargs = self.get_extra_filter_kwargs(request)
  File "[...]/site-packages/django_scim/views.py", line 47, in get_extra_filter_kwargs
    return get_extra_model_filter_kwargs_getter(self.model_cls)
  File "[...]/site-packages/django_scim/views.py", line 43, in model_cls
    return self.__class__.model_cls_getter()
TypeError: unbound method get_user_model() must be called with UsersView instance as first argument (got nothing instead)
[2019/04/14 13:26:16] HTTP GET /scim/v2/Users 500 [0.34, 127.0.0.1:42578]

Is this perhaps an issue for Python2 only?

**Comment by erfaan** [comment]
`model_cls_getter = get_user_model`
Whenever you assign a function to a class object, it becomes a method in python2.

You can retrieve the function object from the unbound method by accessing its `im_func` attribute. Change `views.SCIMView.model_cls` to return:

`self.__class__.model_cls_getter.im_func()`

**Comment by pablodiazgutierrez** [comment]
Thanks @erfaan, I've patched this in https://github.com/15five/django-scim2/pull/23
